//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiggResponsive.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BiggResponsive.Domain.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method is a member of {0}..
        /// </summary>
        internal static string ParameterNullExceptionMessageObjectIs {
            get {
                return ResourceManager.GetString("ParameterNullExceptionMessageObjectIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter {0} on method {1}..
        /// </summary>
        internal static string ParameterNullExceptionMessageOnMethod {
            get {
                return ResourceManager.GetString("ParameterNullExceptionMessageOnMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method expected a non-null, or non-default-value of the type {0}..
        /// </summary>
        internal static string ParameterNullExceptionMethodExpectedNonNull {
            get {
                return ResourceManager.GetString("ParameterNullExceptionMethodExpectedNonNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No parameter name passed, however the following parameters were available at the time the exception was thrown:.
        /// </summary>
        internal static string ParameterNullExceptionNoName {
            get {
                return ResourceManager.GetString("ParameterNullExceptionNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine the failing parameter type, perhaps the name passed was incorrect?.
        /// </summary>
        internal static string ParameterNullExceptionUnableToDetermine {
            get {
                return ResourceManager.GetString("ParameterNullExceptionUnableToDetermine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine the method&apos;s declaring type..
        /// </summary>
        internal static string ParameterNullExceptionUnableToDetermineDeclaringType {
            get {
                return ResourceManager.GetString("ParameterNullExceptionUnableToDetermineDeclaringType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; is too long: it must not exceed {1} chars in length..
        /// </summary>
        internal static string ParameterTooLong {
            get {
                return ResourceManager.GetString("ParameterTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParameterTooShort.
        /// </summary>
        internal static string ParameterTooShort {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
